### ISSUE TITLE
Incompatibility with latest Chisel 2.0

### ISSUE THREAD

**Issue by Painstouch** [Choonster-Minecraft-Mods/ChiselFacades#1]
(Obviously)
Looking towards an update!

https://pastee.org/fed7c

**Comment by Choonster** [comment]
I can't seem to find any information about Chisel 2.0. Could you link the description/download page for me?

**Comment by Painstouch** [comment]
MCF:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2254671-chisel-2
Curseforge: http://minecraft.curseforge.com/mc-mods/225236-chisel-2

2014-11-01 15:36 GMT+01:00 Choonster notifications@github.com:

**Comment by Choonster** [comment]
Thanks. I haven't seen any confirmation from Pokefenn that they plan to stop development on Chisel, so I'll probably add support for Cricket's version as yet another branch rather than replace the Pokefenn-version completely.

**Comment by Painstouch** [comment]
Actually, there is confirmation in the poke's thread afaik, and EoD did
give a thumbs to Cricket for using his fork of asie's fork of Poke's Chisel
version, so it's all legit.

2014-11-01 15:45 GMT+01:00 Choonster notifications@github.com:

**Comment by Choonster** [comment]
Closed by d32bc98cf6a34273bec2afcd95376f1244852201.

**Comment by Choonster** [comment]
Version 1.7.10-2.3-cricket is now available on CurseForge.
