### ISSUE TITLE
Crash with newest Chisel

### ISSUE THREAD

**Issue by AlexPlus117** [Choonster-Minecraft-Mods/ChiselFacades#11]
Hi, my client crashes each time I try to load it with your Chisel Facades and newest tterrag's Chisel. This is the crash-report: http://pastebin.com/PQ1AsPTA

**Comment by Choonster** [comment]
Fixed in 2bd7062d4ae18f1d63ae746c319e5cb34fef3869.

You can now download 1.7.10-2.12-chiselteam from [CurseForge](http://minecraft.curseforge.com/mc-mods/222784-chisel-facades/files/2255081).
