### ISSUE TITLE
Crash when startup

### ISSUE THREAD

**Issue by SinusoidalC** [Choonster-Minecraft-Mods/ChiselFacades#2]
I'm using chisel 2.1.3 chisel facades 2.5 and BC 6.2.2.After crash I looked into my fmllog, and it shows that it is the fault of chisel facades.
CR is here
---- Minecraft Crash Report ----
// There are four lights!

Time: 14-12-3 下午6:30
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: voidstone
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:692)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchFieldError: voidstone
    at com.choonster.chiselfacades.FacadeCreator.init(FacadeCreator.java:247)
    at com.choonster.chiselfacades.ChiselFacades.init(ChiselFacades.java:27)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 361498256 bytes (344 MB) / 995172352 bytes (949 MB) up to 3151495168 bytes (3005 MB)
    JVM Flags: 2 total; -Xincgc -Xmx3072M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 163 mods loaded, 163 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.10.85.1230} [Forge Mod Loader](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.13.2.1230} [Minecraft Forge](forge-1.7.10-10.13.2.1230.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Aroma1997Core{1.0.2.13} [Aroma1997Core]([A]Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BetterFonts{1.1.3} [BetterFonts](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    InputFix{1.7.10-v5} [InputFix](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenEye{0.6} [OpenEye]([F]OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.0.3.71} [Not Enough Items]([NEI]NotEnoughItems-1.7.10-1.0.3.71-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenModsCore{0.6} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Aroma1997CoreHelper{1.0.2.13} [Aroma1997Core|Helper]([A]Aroma1997Core-1.7.10-1.0.2.13.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bdlib{1.5.1.32} [BD Lib]([A]bdlib-mc1710-1.5.1.32.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CoFHCore{1.7.10R3.0.0B8} [CoFH Core]([A]CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized->Initialized
    cookiecore{1.3.0} [Cookie Core]([A]cookiecore-1.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Enchiridion{1.1} [Enchiridion]([A]Enchiridion-1.7.X-1.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IC2{2.2.654-experimental} [IndustrialCraft 2]([IC2]industrialcraft-2-2.2.654-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ImmibisCore{59.0.5} [Immibis Core]([A]immibis-core-59.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle]([A]Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MetallurgyCore{4.0.4} [Metallurgy Core]([A]MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized
    numina{0.4.0.99} [Numina]([A]Numina-0.4.0.99.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenMods{0.6} [OpenMods]([A]OpenModsLib-1.7.10-0.6-snapshot-267.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2]([AE]appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ae2stuff{0.1.0.2} [AE2 Stuff]([AE]ae2stuff-mc1710-0.1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Waila{1.5.5} [Waila]([NEI]Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    extracells{2.1.13} [ExtraCells]([AE]ExtraCells-1.7.10-2.1.13b15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Core{6.2.2} [BuildCraft](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Energy{6.2.2} [BC Energy](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    eureka{2.1} [Eureka](Eureka-1.7.10-2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bcadditions{1.8.1} [Buildcraft Additions]([BC]BuildcraftAdditions-1.7.10-1.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderIO{1.7.10-2.2.2.285} [Ender IO]([BC]EnderIO-1.7.10-2.2.2.285.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ComputerCraft{1.65} [ComputerCraft]([CC]ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forestry{3.2.0.5} [Forestry for Minecraft]([FR]forestry_1.7.10-3.2.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization.notify{1.0} [Factorization Notification System]([T]Factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization{1.7.10-0.8.88.7} [Factorization]([T]Factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Baubles{1.0.1.9} [Baubles](Baubles-1.7.10-1.0.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.2.1.4} [Thaumcraft]([TC]Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation]([WG]ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThermalExpansion{1.7.10R4.0.0B6} [Thermal Expansion]([TE]ThermalExpansion-[1.7.10]4.0.0B6-16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Transport{6.2.2} [BC Transport](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Silicon{6.2.2} [BC Silicon](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LogisticsPipes{0.8.2.83} [Logistics Pipes]([BC]logisticspipes-0.8.2.83.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderStorage{1.4.5.26} [EnderStorage]([O]EnderStorage-1.7.10-1.4.5.26-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Builders{6.2.2} [BC Builders](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Factory{6.2.2} [BC Factory](buildcraft-6.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Railcraft{9.4.0.0} [Railcraft]([RC]Railcraft_1.7.10-9.4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenPeripheralCore{0.5.0} [OpenPeripheralCore]([CC]OpenPeripheralCore-1.7.10-0.5.0-snapshot-169.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenPeripheral{0.2.0} [OpenPeripheralAddons]([CC]OpenPeripheralAddons-1.7.10-0.2.0-snapshot-137.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenPeripheralIntegration{0.1.0} [OpenPeripheralIntegration]([CC]OpenPeripheralIntegration-1.7.10-0.1.0-snapshot-15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AromaBackup{0.0.0.5} [AromaBackup]([F]AromaBackup-1.7.10-0.0.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FastCraft{1.9} [FastCraft]([F]fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks]([F]InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized->Initialized
    journeymap{5.0.0} [JourneyMap]([F]JourneyMap5.0.0_FairPlay_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineTweaker3{3.0.9B} [MineTweaker 3]([F]MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ModTweaker{0.6} [ModTweaker]([F]ModTweaker-1.7.X-0.6-0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MouseTweaks{2.4.4} [Mouse Tweaks]([F]MouseTweaks-2.4.4-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughCodecs{0.3} [NotEnoughCodecs]([F]NotEnoughCodecs-1.7.10-0.3-snapshot-11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TabulaRasa{1.7.10R1.0.1} [Tabula Rasa]([F]TabulaRasa-[1.7.10]1.0.1-3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    zyinhud{1.3.6} [Zyin's HUD]([F]ZyinsHUD-%281.7.10%29-v.1.3.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AWWayofTime{v1.2.1b} [Blood Magic: Alchemical Wizardry]([M]BloodMagic-1.7.10-1.2.1b-1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.1.0.314} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer]([TC]ThaumicTinkerer-2.5-1.7.10-424.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct]([TiC]TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MagicBees{1.7.10-2.1.22} [Magic Bees]([FR]magicbees-1.7.10-2.1.22.jar) Unloaded->Constructed->Pre-initialized->Initialized
    gendustry{1.4.2.46} [GenDustry]([FR]gendustry-mc1710-1.4.2.46.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AdvancedRepulsionSystems{59.0.2} [Advanced Repulsion Systems]([IC2]adv-repulsion-systems-59.0.2[CN].jar) Unloaded->Constructed->Pre-initialized->Initialized
    AdvancedMachines{59.0.2} [Advanced Machines]([IC2]advanced-machines-59.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels]([IC2]AdvancedSolarPanel-1.7.10-3.5.1[TFCN].jar) Unloaded->Constructed->Pre-initialized->Initialized
    CompactSolars{4.4.39.315} [Compact Solar Arrays]([IC2]CompactSolars-1.7.10-4.4.39.315-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GraviSuite{1.7.10-2.0.3} [Graviation Suite]([IC2]GraviSuite-1.7.10-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    mikesquarry{1.7.10-1.0} [Simple-Ic2-Quarry]([IC2]IC2-Quarry-1.7.10-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IC2NuclearControl{2.0.8c} [Nuclear Control 2]([IC2]IC2NuclearControl-2.0.8c.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ihl{0.521} [IHL Tools & Machines for IC2V2]([IC2]ihl-tools_n_machines-0.521-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    voidtech{1.7.10-1.3} [VoidTech]([IC2]VoidTech-1.7.10_1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WaterPower{0.3e} [WaterPower]([IC2]WaterPower-0.3e-8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    adventurersamulets{1.7.10-1.5.0b} [Adventurer's Amulets]([M]AdventurersAmulets-1.7.10-1.5.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    witchery{0.20.6} [Witchery]([M]witchery-1.7.10-0.20.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons{1.12.3.11} [NEI Addons]([NEI]neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany]([NEI]neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry]([NEI]neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables]([NEI]neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo]([NEI]neiaddons-mc1710-1.12.3.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
    neiintegration{1.0.1} [NEI Integration]([NEI]NEIIntegration-MC1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    thaumcraftneiplugin{1.7.10-1.6a} [Thaumcraft NEI Plugin]([NEI]thaumcraftneiplugin-1.7.10-1.6a.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mariculture{1.2.3d} [Mariculture]([T]Mariculture-1.7.10-1.2.3d.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TSteelworks{1.7.10-1.0.6} [Tinkers' Steelworks]([TiC]TSteelworks-1.7.10-1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WailaHarvestability{1.1.0} [Waila Harvestability]([NEI]WailaHarvestability-mc1.7.x-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BetterChests{1.1.1.8} [BetterChests]([O]BetterChests-1.7.10-1.1.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.9.1} [BiblioCraft]([O]BiblioCraft[v1.9.1][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition]([O]BiblioWoods[Forestry][v1.7].jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.2.0} [Natura]([WG]natura-1.7.10-2.2.0-b1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition]([O]BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed->Pre-initialized->Initialized
    CarpentersBlocks{3.3.3} [Carpenter's Blocks]([O]Carpenter's Blocks v3.3.3 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ChickenChunks{1.3.4.14} [ChickenChunks]([O]ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    chisel{2.1.3} [Chisel]([O]Chisel 2-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ChiselFacades{1.7.10-2.5-cricket} [Chisel Facades]([O]ChiselFacades-1.7.10-2.5-cricket.jar) Unloaded->Constructed->Pre-initialized->Errored
    IronChest{6.0.62.742} [Iron Chest]([O]ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    JABBA{1.1.4} [JABBA]([O]Jabba-1.1.4_1.7.10[CN].jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenBlocks{1.3} [OpenBlocks]([O]OpenBlocks-1.7.10-1.3-snapshot-510.jar) Unloaded->Constructed->Pre-initialized->Initialized
    thaumcarpentry{0.0.1.5-1.7.10} [Thaumcarpentry]([O]Thaumcarpentry-0.0.1.5-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Translocator{1.1.1.13} [Translocator]([O]Translocator-1.7.10-1.1.1.13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    warpbook{2.0.null} [Warp Book]([O]warpbook-1.7.10_2.0.36.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights{1.3.7} [Dynamic Lights]([OF]DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module]([OF]DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module]([OF]DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module]([OF]DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module]([OF]DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_mobEquipment{1.0.7} [Dynamic Lights Mob Equipment Light Module]([OF]DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module]([OF]DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light]([OF]DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module]([OF]DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module]([OF]DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MrTJPCoreMod{1.0} [MrTJPCoreMod](MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Core{4.5.7.58} [ProjectRed]([PR]ProjectRed-1.7.10-4.5.7.58-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Transmission{4.5.7.58} [ProjectRed-Transmission]([PR]ProjectRed-1.7.10-4.5.7.58-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Transportation{4.5.7.58} [ProjectRed-Transportation]([PR]ProjectRed-1.7.10-4.5.7.58-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Exploration{4.5.7.58} [ProjectRed-Exploration]([PR]ProjectRed-1.7.10-4.5.7.58-World.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Compatibility{4.5.7.58} [ProjectRed-Compatibility]([PR]ProjectRed-1.7.10-4.5.7.58-Compat.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Integration{4.5.7.58} [ProjectRed-Integration]([PR]ProjectRed-1.7.10-4.5.7.58-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Illumination{4.5.7.58} [ProjectRed-Illumination]([PR]ProjectRed-1.7.10-4.5.7.58-Lighting.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Expansion{4.5.7.58} [ProjectRed-Expansion]([PR]ProjectRed-1.7.10-4.5.7.58-Mechanical_beta.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraUtilities{1.2.0} [Extra Utilities]([T]extrautilities-1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization.misc{1.7.10-0.8.88.7} [Factorization Miscellaneous Nonsense]([T]Factorization-1.7.10-0.8.88.7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    framez{0.2} [Framez]([T]Framez-1.7.10-0.2-12-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    advgenerators{0.9.6.27} [Advanced Generators]([T]generators-mc1710-0.9.6.27.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Botania{r1.3-138} [Botania]([TM]Botania r1.3-138.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Metallurgy{4.0.6} [Metallurgy 4]([T]Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PowerConverters{1.7.10-3.0.2.38} [Power Converters]([T]PowerConverters-1.7.10-3.0.2.38.jar) Unloaded->Constructed->Pre-initialized->Initialized
    pressure{1.0.1.48} [Pressure Pipes]([T]pressure-mc1710-1.0.1.48.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RefinedRelocation{1.0.6h} [Refined Relocation]([T]RefinedRelocation-1.7.10-1.0.6h.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RIO{1.7.1} [RemoteIO]([T]RemoteIO-1.7.10-1.7.1.B80-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    StevesCarts{2.0.0.b18} [Steve's Carts 2]([T]StevesCarts2.0.0.b18.jar) Unloaded->Constructed->Pre-initialized->Initialized
    StevesFactoryManager{A93} [Steve's Factory Manager]([T]StevesFactoryManagerA93.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WR-CBE|Core{1.4.1.9} [WR-CBE Core]([T]WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons]([T]WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic]([T]WR-CBE-1.7.10-1.4.1.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Automagy{0.14} [Automagy]([TC]Automagy-1.7.10-0.14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EMT{2.0.0Alpha4} [Electro-Magic Tools]([TC]ElectroMagicTools-1.7.10-2.0.0Alpha-28.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForbiddenMagic{1.7.10-0.55} [Forbidden Magic]([TC]Forbidden Magic-1.7.10-0.55.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Magistics{0.6.0} [Magistics]([TC]Magistics-1.7.10-0.6.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NodalMechanics{1.7.10R1.0} [NodalMechanics]([TC]NodalMechanics-1.7-1.0-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    thaumcraftgates{1.4.0} [Thaumcraft Gates]([TC]ThaumcraftGates-1.4.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects]([TC]ThaumcraftMobAspects-1.7.2-2A.jar) Unloaded->Constructed->Pre-initialized->Initialized
    thaumicenergistics{0.8.7b} [Thaumic Energistics]([TC]thaumicenergistics-0.8.7b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicExploration{0.6.0} [Thaumic Exploration]([TC]ThaumicExploration-1.7.10-1.1-31.jar) Unloaded->Constructed->Pre-initialized->Initialized
    powersuits{0.11.0.175} [MachineMuse's Modular Powersuits]([TE]ModularPowersuits-0.11.0.175.jar) Unloaded->Constructed->Pre-initialized->Initialized
    powersuitaddons{@VERSION@} [Modular Powersuits Addon]([TE]powersuitaddons-1.7.10-901.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RedstoneArsenal{1.7.10R1.1.0RC1} [Redstone Arsenal]([TE]RedstoneArsenal-[1.7.10]1.1.0RC1-19.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TiCTooltips{1.1.11b} [TiC Tooltips]([TiC]TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TMechworks{1.7.10-86.e500b88} [Tinkers' Mechworks]([TiC]TMechworks-1.7.10-0.2.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    meteors{2.13.1} [Falling Meteors]([WG]meteors-1.7.10-2.13.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NetherOres{1.7.10R2.3.0RC3} [Nether Ores]([WG]NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{2.3.2} [The Twilight Forest]([WG]twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    thebombzenapi{2.4.1} [ThebombzenAPI](ThebombzenAPI-v2.4.1-mc1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    enchantview{4.0.4} [EnchantView](EnchantView-v4.0.4-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    enchvil{1.0} [Enchvil Mod](Enchvil-Mod-1.7.10＆2-CN.jar) Unloaded->Constructed->Pre-initialized->Initialized
    McMultipart{1.1.0.314} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IguanaTweaksTConstruct{1.7.10-2.0.6} [Iguana Tinker Tweaks]([TiC]IguanaTinkerTweaks-1.7.10-2.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    aobd{2.3.4} [Another One Bites The Dust]([TM]AOBD-2.3.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.1.0.314} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenModsLib crash transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:ENABLED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Mantle Environment: Environment healthy.
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8

**Comment by Choonster** [comment]
Fixed in bd41619ce3e4b114632ac13181831b54888c68ed, thanks for the report.

No actual code changes in this version, just a recompile and version bump because Void Stone changed types.

**Comment by SinusoidalC** [comment]
nice ,but where's download?

**Comment by Choonster** [comment]
On CurseForge, as usual. Is it not showing up or not showing as approved for you?

I might upload the mod to the GitHub release section as well.

**Comment by Choonster** [comment]
All releases should now have universal (obfuscated) JARs attached to them.

I probably won't offer developer (deobfuscated) JARs unless there's a large demand for them (though I doubt there's many people who want to develop an AddOn mod for an AddOn mod).
