### ISSUE TITLE
Crash with Chisel 2 2.2.0 by TheCricket26

### ISSUE THREAD

**Issue by Hazado** [Choonster-Minecraft-Mods/ChiselFacades#5]
http://minecraft.curseforge.com/mc-mods/225236-chisel-2/files
Crash Log
http://pastebin.com/tUzQAJTD

**Comment by JasonMcRay** [comment]
Can confirm this. It is because Chisel changed the name of packages from info.jbcs to com.cricketcraft

**Comment by Choonster** [comment]
I've had a fix for this on GitHub for 10 days, but I was waiting for Cricket to release his new version before I released mine. Now that it's out, I'll do a release very soon.

**Comment by Choonster** [comment]
Fixed by e1dc9c3c2107b994167eaf3a971ba9b66c7e1d56 / 4618e8be03be8e4bda911b5ae968bff48a9aa7b2.
