### ISSUE TITLE
Crash with Chisel v2.2.1

### ISSUE THREAD

**Issue by xJon** [Choonster-Minecraft-Mods/ChiselFacades#6]
Crash log: http://pastebin.com/pN8es7s5
thanks!

**Comment by Choonster** [comment]
You're using an old version of Chisel Facades (2.6-cricket). The latest Cricket version is 2.7-cricket, which doesn't have this issue.

**Comment by xJon** [comment]
Yep, I just found it out. wanted to close it myself but you're sonic.
thank you anyway and forgive me for my mistake!
