### ISSUE TITLE
Unable to craft facades on SMP.

### ISSUE THREAD

**Issue by Kubuxu** [Choonster-Minecraft-Mods/ChiselFacades#8]
Version: 2.7-cricket

**Comment by Choonster** [comment]
Do non-Chisel Facades work?

**Comment by marcin212** [comment]
yes (I play with Kubuxu)

**Comment by Choonster** [comment]
I can confirm that most Facades of Chisel blocks can't be crafted in multiplayer. Variations with metadata 0 seem to work, though.

**Comment by Choonster** [comment]
I've filed an issue with BuildCraft (BuildCraft/BuildCraft#2389).

**Comment by Choonster** [comment]
This will be fixed in the next BuildCraft version
